name: Build and release binary
on:
  push:
    tags:
      - 'v*'
    paths:
      - '.github/workflows/build.yml'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Golang
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
          cache: true
      - name: Create package directory
        run: mkdir -p bin
      - name: Build binary
        run: go build -o bin/pjsekai-overlay.exe .
      - name: Copy assets
        run: cp -r assets bin/assets
      - name: Build zip
        run: 7z a -tzip pjsekai-overlay.zip bin

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            pjsekai-overlay.zip
