name: Check code
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Golang
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
          cache: true
      - name: Check formatting
        run: |
          go vet .
          [[ -z $(gofmt -l .) ]] || { echo "Go code is not formatted"; exit 1; }

